sap.ui.define([
	"sap/ui/core/UIComponent",
	"sap/ui/Device",
	"salescloud/model/models"
], function (UIComponent, Device, models) {
	"use strict";

	return UIComponent.extend("salescloud.Component", {

		metadata: {
			manifest: "json"
		},

		/**
		 * The component is initialized by UI5 automatically during the startup of the app and calls the init method once.
		 * @public
		 * @override
		 */
		init: function () {
			// call the base component's init function
			UIComponent.prototype.init.apply(this, arguments);

			// enable routing
			this.getRouter().initialize();

			// set the device model
            this.setModel(models.createDeviceModel(), "device");
            var oData = {
				"aperturaPollVerdad": [],
				"totalTablaReproductora": [{
					"cantidad": "0"
				}],
				"table_cuentas": [{"name":"Irwinn Furneaux","city":"Itaporanga","country":"Brazil","mainContac":"Shurlock Durrell","registeredBy":"sdurrell0","state":false},
                                {"name":"Eilis Lambkin","city":"Cabanbanan","country":"Philippines","mainContac":"Hastie Kynman","registeredBy":"hkynman18","state":true},
                                {"name":"Faun Noe","city":"Parczew","country":"Poland","mainContac":"Lauryn Lydden","registeredBy":"llydden19","state":true},
                                {"name":"Hillary Jeeves","city":"Brinkmann","country":"Argentina","mainContac":"Madelon Sotworth","registeredBy":"msotworth1a","state":true},
                                {"name":"Cassy Spreag","city":"Heze","country":"China","mainContac":"Steffie Livezey","registeredBy":"slivezey1b","state":false},
                                {"name":"Anna-diane Das","city":"Fredericton","country":"Canada","mainContac":"Waiter Chatto","registeredBy":"wchatto1c","state":true},
                                {"name":"Stacy Van Castele","city":"Karangkancana","country":"Indonesia","mainContac":"Jillian Delgadillo","registeredBy":"jdelgadillo1d","state":false}],
				"table_contactos": [{"name":"Barry Sambell","count":"bsambell0","role":"Construction Worker","area":"Crawler","telephone":"0168-0803","phone":"797-20-3011","state":true},
{"name":"Bowie Mitchenson","count":"bmitchenson17","role":"Engineer","area":"Trencher","telephone":"37000-275","phone":"306-80-9103","state":false},
{"name":"Ernestine Erskin","count":"eerskin18","role":"Surveyor","area":"Excavator","telephone":"55292-911","phone":"614-38-7728","state":true},
{"name":"Vite Gilburt","count":"vgilburt19","role":"Estimator","area":"Bulldozer","telephone":"47682-933","phone":"359-73-4877","state":true},
{"name":"Karlik Hanham","count":"khanham1a","role":"Estimator","area":"Bulldozer","telephone":"58411-115","phone":"422-09-9988","state":true},
{"name":"Benedetta Fyfield","count":"bfyfield1b","role":"Subcontractor","area":"Scraper","telephone":"49288-0051","phone":"180-11-8693","state":false},
{"name":"Ignaz Breadon","count":"ibreadon1c","role":"Construction Foreman","area":"Dump Truck","telephone":"0527-1768","phone":"718-09-6060","state":false},
                                    {"name":"Uri Botly","count":"ubotly1d","role":"Architect","area":"Bulldozer","telephone":"76214-047","phone":"813-72-1568","state":false}],
                "table_clientes":[{"name":"Patrizio Batte","telephone":"66582-321","phone":"697-06-4836","email":"pbatte0@taobao.com","address":"76739 Mesta Trail","state":false},
{"name":"Cecil Danilchev","telephone":"64990-605","phone":"897-98-0559","email":"cdanilchev17@nih.gov","address":"240 Ridgeway Park","state":true},
{"name":"Filide Jotcham","telephone":"60913-999","phone":"171-47-9184","email":"fjotcham18@theglobeandmail.com","address":"7913 Darwin Hill","state":false},
{"name":"Karlotta Fullard","telephone":"52544-940","phone":"324-26-9115","email":"kfullard19@google.co.uk","address":"42469 Hoepker Lane","state":false},
{"name":"Harwell Agus","telephone":"66758-130","phone":"166-54-9948","email":"hagus1a@cocolog-nifty.com","address":"27 Gale Plaza","state":true},
{"name":"Felicity Leggan","telephone":"52083-628","phone":"426-94-7764","email":"fleggan1b@dmoz.org","address":"30 Oak Valley Plaza","state":true},
{"name":"Carolina Mc Andrew","telephone":"67046-251","phone":"459-24-7480","email":"cmc1c@networkadvertising.org","address":"5 Hansons Alley","state":false},
                                {"name":"Culver Bonass","telephone":"0245-0003","phone":"347-02-2129","email":"cbonass1d@nature.com","address":"1052 Farwell Point","state":true}],
                "table_group":[{"name":"VP Product Management","createdBy":"Georgetta","changedBy":"Simonazzi","total":1,"state":false,"id":1},
{"name":"Systems Administrator II","createdBy":"Tomasina","changedBy":"Woodings","total":44,"state":true,"id":44},
{"name":"Account Executive","createdBy":"Brand","changedBy":"Rate","total":45,"state":false,"id":45},
{"name":"Computer Systems Analyst II","createdBy":"Gabie","changedBy":"Boerderman","total":46,"state":true,"id":46},
{"name":"Research Associate","createdBy":"Duane","changedBy":"Stonehewer","total":47,"state":false,"id":47},
{"name":"Health Coach II","createdBy":"Marie-jeanne","changedBy":"Bettenson","total":48,"state":false,"id":48},
{"name":"Developer III","createdBy":"Octavia","changedBy":"Kidstoun","total":49,"state":true,"id":49},
                            {"name":"Accounting Assistant IV","createdBy":"Ernie","changedBy":"Wearn","total":50,"state":true,"id":50}],      
                "table_empleado":[{"name":"Patsy Fennelow","rol":"Nurse","Department":"Support","email":"pfennelow0@bloglovin.com","telephone":"(309) 7166924","phone":"258 915 0203"},
{"name":"Cesare Clyma","rol":"Tax Accountant","Department":"Product Management","email":"cclyma18@redcross.org","telephone":"(355) 7728591","phone":"761 178 3997"},
{"name":"Joshua Rossant","rol":"Librarian","Department":"Business Development","email":"jrossant19@vimeo.com","telephone":"(564) 6625027","phone":"124 323 5762"},
{"name":"Rafe Pearl","rol":"Dental Hygienist","Department":"Accounting","email":"rpearl1a@dell.com","telephone":"(288) 1705530","phone":"296 980 6754"},
{"name":"Seward Greenhow","rol":"Occupational Therapist","Department":"Sales","email":"sgreenhow1b@hatena.ne.jp","telephone":"(435) 5338488","phone":"917 379 4335"},
{"name":"Leta Bettaney","rol":"Quality Control Specialist","Department":"Support","email":"lbettaney1c@jiathis.com","telephone":"(125) 4363726","phone":"591 447 3449"},
                            {"name":"Vail Drover","rol":"Quality Control Specialist","Department":"Business Development","email":"vdrover1d@squarespace.com","telephone":"(342) 6170444","phone":"249 269 6275"}],
                "table_socios":[{"namepartner":"Stavro Fenty","state":false,"city":"Anjirserapat","country":"Indonesia","contact":"Stavro","namecontact":"Collins, Zemlak and Parisian","telephone":"(481) 5863585","phone":"377 684 3799","email":"sfenty0@list-manage.com"},
{"namepartner":"Zebadiah Shoubridge","state":false,"city":"Novi Slankamen","country":"Serbia","contact":"Zebadiah","namecontact":"Schuster LLC","telephone":"(606) 5804202","phone":"400 954 8292","email":"zshoubridge1@desdev.cn"},
{"namepartner":"Claudian Coppock.","state":false,"city":"Zhuoshui","country":"China","contact":"Claudian","namecontact":"Haley-Bins","telephone":"(397) 6375487","phone":"838 894 3568","email":"ccoppock2@github.io"},
{"namepartner":"Ray Bycraft","state":false,"city":"Suzuka","country":"Japan","contact":"Ray","namecontact":"Hettinger-McLaughlin","telephone":"(669) 7669959","phone":"368 109 3742","email":"rbycraft3@vk.com"},
{"namepartner":"Fabian Sivewright","state":true,"city":"Yên Mỹ","country":"Vietnam","contact":"Fabian","namecontact":"Hilpert LLC","telephone":"(241) 2462981","phone":"772 750 8978","email":"fsivewright4@nifty.com"},
{"namepartner":"Stillman Eschalotte","state":true,"city":"Kampong Chhnang","country":"Cambodia","contact":"Stillman","namecontact":"Schroeder-Torp","telephone":"(278) 1299713","phone":"978 419 6427","email":"seschalotte5@sun.com"},
{"namepartner":"Lockwood Feragh","state":false,"city":"Kafr Sawm","country":"Jordan","contact":"Lockwood","namecontact":"Lowe-Kutch","telephone":"(699) 2323634","phone":"667 557 3091","email":"lferagh6@ustream.tv"},
{"namepartner":"Patin Hickin","state":false,"city":"Wuluquele","country":"China","contact":"Patin","namecontact":"Mann LLC","telephone":"(145) 2633412","phone":"374 501 9382","email":"phickin7@lycos.com"},
{"namepartner":"Harvey Hampshire","state":true,"city":"Kertosari","country":"Indonesia","contact":"Harvey","namecontact":"Beatty Inc","telephone":"(899) 8338255","phone":"685 171 4573","email":"hhampshire8@ox.ac.uk"},
                                {"namepartner":"Arch Jayme","state":true,"city":"Gardēz","country":"Afghanistan","contact":"Arch","namecontact":"Swift-Mueller","telephone":"(300) 6616205","phone":"224 424 7160","email":"ajayme9@mapy.cz"}],
                "table_campania":[{"name":"Olivette Leving","channel":1,"target":"Kazio","state":true,"execution":true,"responsable":"Olivette"},
{"name":"Nicholle Walthew","channel":2,"target":"Skaboo","state":true,"execution":false,"responsable":"Nicholle"},
{"name":"Jobie Hazael","channel":3,"target":"Lajo","state":false,"execution":false,"responsable":"Jobie"},
{"name":"Gerry Stanyon","channel":4,"target":"Voonte","state":false,"execution":true,"responsable":"Gerry"},
{"name":"Feliza Clery","channel":5,"target":"Rooxo","state":false,"execution":true,"responsable":"Feliza"},
{"name":"Zoe Aymerich","channel":6,"target":"Jetpulse","state":false,"execution":true,"responsable":"Zoe"},
{"name":"Dion Oleshunin","channel":7,"target":"Flashset","state":true,"execution":true,"responsable":"Dion"},
{"name":"Avie Wewell","channel":8,"target":"Gabtype","state":true,"execution":false,"responsable":"Avie"},
{"name":"Berget Smoote","channel":9,"target":"Jetpulse","state":true,"execution":true,"responsable":"Berget"},
                                {"name":"Flory Pietasch","channel":10,"target":"Twitterwire","state":true,"execution":false,"responsable":"Flory"}],
                "table_gestioncontenido":[{"name":"Emlynn January 1st","state":true,"content":"CNY","category":"Sportvan G30","createBy":"January 1st","modifiedBy":"Emlynn"},
{"name":"Burk Pitherick","state":false,"content":"USD","category":"3 Series","createBy":"Pitherick","modifiedBy":"Burk"},
{"name":"Matelda Marcam","state":true,"content":"CNY","category":"Integra","createBy":"Marcam","modifiedBy":"Matelda"},
{"name":"Alidia Towson","state":false,"content":"CAD","category":"Continental Super","createBy":"Towson","modifiedBy":"Alidia"},
{"name":"Burgess Wrack","state":true,"content":"CAD","category":"Ram Van 1500","createBy":"Wrack","modifiedBy":"Burgess"},
{"name":"Welbie Bingle","state":false,"content":"EUR","category":"F-Series Super Duty","createBy":"Bingle","modifiedBy":"Welbie"},
{"name":"Elayne Jendrich","state":true,"content":"ALL","category":"Avanti","createBy":"Jendrich","modifiedBy":"Elayne"},
{"name":"Immanuel Bohlsen","state":false,"content":"TZS","category":"Avenger","createBy":"Bohlsen","modifiedBy":"Immanuel"},
{"name":"Poppy Fielders","state":false,"content":"BAM","category":"V50","createBy":"Fielders","modifiedBy":"Poppy"},
                                        {"name":"Claudia Cleere","state":true,"content":"PLN","category":"Sierra 3500","createBy":"Cleere","modifiedBy":"Claudia"}],
                "table_leads":[{"namelead":"Tres-Zap","namecontact":"Darren","capaniacliente":false,"nivelcalificacion":false,"state":1,"priority":1,"startdate":"4/12/2021","finishdate":"2/21/2021","responsable":"Darren Ormrod"},
{"namelead":"Bigtax","namecontact":"Lyle","capaniacliente":false,"nivelcalificacion":false,"state":2,"priority":2,"startdate":"8/29/2020","finishdate":"3/29/2021","responsable":"Lyle Summerfield"},
{"namelead":"Greenlam","namecontact":"Osborn","capaniacliente":true,"nivelcalificacion":false,"state":3,"priority":3,"startdate":"12/13/2020","finishdate":"4/16/2021","responsable":"Osborn Edmead"},
{"namelead":"Greenlam","namecontact":"Denny","capaniacliente":true,"nivelcalificacion":false,"state":4,"priority":4,"startdate":"1/15/2021","finishdate":"5/29/2021","responsable":"Denny Loding"},
{"namelead":"Greenlam","namecontact":"Alistair","capaniacliente":true,"nivelcalificacion":true,"state":5,"priority":5,"startdate":"12/29/2020","finishdate":"8/12/2020","responsable":"Alistair Grogona"},
{"namelead":"Bamity","namecontact":"Weider","capaniacliente":false,"nivelcalificacion":false,"state":6,"priority":6,"startdate":"11/12/2020","finishdate":"7/14/2021","responsable":"Weider Simonaitis"},
{"namelead":"Ronstring","namecontact":"Simone","capaniacliente":true,"nivelcalificacion":false,"state":7,"priority":7,"startdate":"9/23/2020","finishdate":"11/2/2020","responsable":"Simone Manuello"},
{"namelead":"Subin","namecontact":"Hagen","capaniacliente":false,"nivelcalificacion":true,"state":8,"priority":8,"startdate":"10/15/2020","finishdate":"4/27/2021","responsable":"Hagen Bartalot"},
{"namelead":"Kanlam","namecontact":"Chas","capaniacliente":true,"nivelcalificacion":true,"state":9,"priority":9,"startdate":"1/25/2021","finishdate":"3/20/2021","responsable":"Chas Starkings"},
                            {"namelead":"Solarbreeze","namecontact":"Stephan","capaniacliente":true,"nivelcalificacion":true,"state":10,"priority":10,"startdate":"10/23/2020","finishdate":"2/24/2021","responsable":"Stephan Vickerstaff"}],
                "table_oportunidades":[{"name":"Cookley","accounts":"Forrester","closingdate":"10/31/2020","sales":1,"responsable":"Forrester Blundin","state":1},
{"name":"Bamity","accounts":"Reynold","closingdate":"7/24/2021","sales":2,"responsable":"Reynold Dunstall","state":2},
{"name":"Zamit","accounts":"Karl","closingdate":"11/12/2020","sales":3,"responsable":"Karl Keppel","state":3},
{"name":"Biodex","accounts":"Inglis","closingdate":"3/3/2021","sales":4,"responsable":"Inglis Tofano","state":4},
{"name":"Gembucket","accounts":"Boniface","closingdate":"7/7/2021","sales":5,"responsable":"Boniface Auty","state":5},
{"name":"Namfix","accounts":"Gerhardt","closingdate":"1/17/2021","sales":6,"responsable":"Gerhardt Stamp","state":6},
{"name":"Flowdesk","accounts":"Lionel","closingdate":"11/15/2020","sales":7,"responsable":"Lionel Clemerson","state":7},
{"name":"Zaam-Dox","accounts":"Caz","closingdate":"1/13/2021","sales":8,"responsable":"Caz Sterling","state":8},
{"name":"Flexidy","accounts":"Durant","closingdate":"3/17/2021","sales":9,"responsable":"Durant Rowlstone","state":9},
                                    {"name":"Trippledex","accounts":"Huey","closingdate":"7/6/2021","sales":10,"responsable":"Huey Dufty","state":10}],
                "table_forecasts":[{"name":"Ventosanzap","responsable":"Kiersten Shepton","moneda":"Won","from":"3/4/2021","until":"1/25/2021"},
{"name":"Zontrax","responsable":"Kim Moscrop","moneda":"Peso","from":"1/10/2021","until":"5/12/2021"},
{"name":"Transcof","responsable":"Rafaela Tytcomb","moneda":"Yuan Renminbi","from":"10/5/2020","until":"9/23/2020"},
{"name":"Cardguard","responsable":"Denni Kempe","moneda":"Peso","from":"5/13/2021","until":"5/3/2021"},
{"name":"Zontrax","responsable":"Clayborn Dibsdale","moneda":"Rupiah","from":"2/22/2021","until":"4/19/2021"},
{"name":"Wrapsafe","responsable":"Hildagard Easter","moneda":"Kuna","from":"9/10/2020","until":"2/9/2021"},
{"name":"Toughjoyfax","responsable":"Asher Grestye","moneda":"Yuan Renminbi","from":"5/11/2021","until":"2/11/2021"},
{"name":"Toughjoyfax","responsable":"Darsie McKeggie","moneda":"Krona","from":"7/28/2021","until":"2/9/2021"},
{"name":"Bitwolf","responsable":"Maximilien Blacklawe","moneda":"Rupiah","from":"5/1/2021","until":"8/29/2020"},
                                {"name":"Trippledex","responsable":"Justen Tudball","moneda":"Yuan Renminbi","from":"12/22/2020","until":"11/17/2020"}],
                "table_listaprecios":[{"name":"Glass","moneda":"Yuan Renminbi","from":"12/8/2020","until":"10/20/2020"},
{"name":"Aluminum","moneda":"Hryvnia","from":"3/22/2021","until":"10/14/2020"},
{"name":"Aluminum","moneda":"Peso","from":"12/3/2020","until":"3/20/2021"},
{"name":"Steel","moneda":"Rupiah","from":"12/22/2020","until":"12/28/2020"},
{"name":"Wood","moneda":"Rupiah","from":"5/28/2021","until":"1/29/2021"},
{"name":"Stone","moneda":"Yuan Renminbi","from":"11/25/2020","until":"6/28/2021"},
{"name":"Plastic","moneda":"Ruble","from":"10/11/2020","until":"3/28/2021"},
{"name":"Granite","moneda":"Dirham","from":"4/15/2021","until":"11/19/2020"},
{"name":"Vinyl","moneda":"Hryvnia","from":"3/31/2021","until":"2/11/2021"},
                                    {"name":"Plastic","moneda":"Yuan Renminbi","from":"10/22/2020","until":"7/26/2021"}],
                "table_reuniones":[{"asunto":"jp.ameblo.Andalax","state":false,"startdate":"4/17/2021","enddate":"7/8/2021","accounts":"vstoppe0","maincontact":"Stoppe","telephono":"686-237-8567","note":"forecast"},
{"asunto":"cn.google.Andalax","state":false,"startdate":"9/18/2020","enddate":"6/18/2021","accounts":"kreven1","maincontact":"Reven","telephono":"477-763-9968","note":"local area network"},
{"asunto":"ru.vkontakte.Tres-Zap","state":false,"startdate":"1/16/2021","enddate":"6/16/2021","accounts":"cmcmichell2","maincontact":"McMichell","telephono":"146-120-9317","note":"neutral"},
{"asunto":"com.hubpages.Stronghold","state":false,"startdate":"12/30/2020","enddate":"11/16/2020","accounts":"sficken3","maincontact":"Ficken","telephono":"133-272-9216","note":"analyzer"},
{"asunto":"com.weebly.Rank","state":false,"startdate":"5/17/2021","enddate":"8/4/2020","accounts":"acornfield4","maincontact":"Cornfield","telephono":"905-224-0545","note":"Self-enabling"},
{"asunto":"org.w3.Overhold","state":false,"startdate":"12/12/2020","enddate":"7/13/2021","accounts":"gyitshak5","maincontact":"Yitshak","telephono":"737-832-4970","note":"Operative"},
{"asunto":"gov.cdc.Konklab","state":false,"startdate":"3/4/2021","enddate":"5/9/2021","accounts":"cgoodfellow6","maincontact":"Goodfellow","telephono":"703-633-4183","note":"customer loyalty"},
{"asunto":"com.vimeo.Quo Lux","state":false,"startdate":"4/15/2021","enddate":"3/28/2021","accounts":"yloncaster7","maincontact":"Loncaster","telephono":"520-446-7913","note":"disintermediate"},
{"asunto":"com.about.Duobam","state":false,"startdate":"2/28/2021","enddate":"4/12/2021","accounts":"hjennaway8","maincontact":"Jennaway","telephono":"884-595-7255","note":"hierarchy"},
                                {"asunto":"int.who.Y-find","state":true,"startdate":"4/20/2021","enddate":"12/8/2020","accounts":"lbullimore9","maincontact":"Bullimore","telephono":"991-933-3020","note":"upward-trending"}],
                "table_llamadas":[{"asunto":"Health Coach I","state":true,"startdate":"7/25/2021","responsable":"Whitlow","client":"pwhitlow0","telephono":"108-711-8529","note":"tertiary"},
{"asunto":"Technical Writer","state":true,"startdate":"1/22/2021","responsable":"Woodroffe","client":"swoodroffe1","telephono":"101-799-6252","note":"tertiary"},
{"asunto":"Research Nurse","state":false,"startdate":"9/7/2020","responsable":"Tyce","client":"ftyce2","telephono":"856-338-7712","note":"Graphical User Interface"},
{"asunto":"Environmental Tech","state":false,"startdate":"5/15/2021","responsable":"Kulic","client":"dkulic3","telephono":"935-301-7100","note":"Optimized"},
{"asunto":"Administrative Officer","state":false,"startdate":"5/12/2021","responsable":"Robke","client":"brobke4","telephono":"109-672-2758","note":"circuit"},
{"asunto":"Environmental Specialist","state":true,"startdate":"6/20/2021","responsable":"Jewis","client":"kjewis5","telephono":"510-620-7835","note":"functionalities"},
{"asunto":"Account Coordinator","state":false,"startdate":"9/15/2020","responsable":"Courtois","client":"hcourtois6","telephono":"317-888-2397","note":"flexibility"},
{"asunto":"Director of Sales","state":true,"startdate":"5/20/2021","responsable":"O'Moylane","client":"tomoylane7","telephono":"275-426-9126","note":"Ergonomic"},
{"asunto":"Information Systems Manager","state":true,"startdate":"10/17/2020","responsable":"McMinn","client":"tmcminn8","telephono":"106-721-5729","note":"24/7"},
                                {"asunto":"Pharmacist","state":true,"startdate":"7/13/2021","responsable":"Tsar","client":"stsar9","telephono":"562-477-0015","note":"extranet"}],
                "table_tareas":[{"asunto":"Chief Design Engineer","state":true,"startdate":"8/12/2020","expirationdate":"4/7/2021","enddate":"10/14/2020","accounts":"Gristock","telephono":"466-867-8287","responsable":"Clem","createby":"cgristock0","updateby":"cgristock0","completby":"cgristock0","note":"service-desk"},
{"asunto":"Legal Assistant","state":false,"startdate":"1/29/2021","expirationdate":"4/12/2021","enddate":"6/16/2021","accounts":"Clementucci","telephono":"248-227-9166","responsable":"Leela","createby":"lclementucci1","updateby":"lclementucci1","completby":"lclementucci1","note":"Automated"},
{"asunto":"Analyst Programmer","state":true,"startdate":"4/8/2021","expirationdate":"1/1/2021","enddate":"8/11/2020","accounts":"Doret","telephono":"160-910-9201","responsable":"Cassandry","createby":"cdoret2","updateby":"cdoret2","completby":"cdoret2","note":"Organic"},
{"asunto":"Structural Analysis Engineer","state":true,"startdate":"10/28/2020","expirationdate":"4/5/2021","enddate":"7/12/2021","accounts":"Woodstock","telephono":"708-700-0333","responsable":"Shelden","createby":"swoodstock3","updateby":"swoodstock3","completby":"swoodstock3","note":"core"},
{"asunto":"Geologist I","state":true,"startdate":"8/21/2020","expirationdate":"10/8/2020","enddate":"5/15/2021","accounts":"Spadazzi","telephono":"730-998-8222","responsable":"Mellisa","createby":"mspadazzi4","updateby":"mspadazzi4","completby":"mspadazzi4","note":"system engine"},
{"asunto":"Accountant IV","state":false,"startdate":"12/29/2020","expirationdate":"9/24/2020","enddate":"5/1/2021","accounts":"Boynes","telephono":"719-391-5325","responsable":"Joyous","createby":"jboynes5","updateby":"jboynes5","completby":"jboynes5","note":"next generation"},
{"asunto":"Tax Accountant","state":true,"startdate":"8/4/2020","expirationdate":"5/14/2021","enddate":"12/26/2020","accounts":"Casford","telephono":"748-558-9229","responsable":"Wrennie","createby":"wcasford6","updateby":"wcasford6","completby":"wcasford6","note":"executive"},
{"asunto":"Account Representative I","state":false,"startdate":"7/29/2021","expirationdate":"6/26/2021","enddate":"5/31/2021","accounts":"Lyon","telephono":"371-937-4533","responsable":"Sharon","createby":"slyon7","updateby":"slyon7","completby":"slyon7","note":"regional"},
{"asunto":"Director of Sales","state":true,"startdate":"7/15/2021","expirationdate":"3/15/2021","enddate":"3/12/2021","accounts":"Titterell","telephono":"582-935-9070","responsable":"Janella","createby":"jtitterell8","updateby":"jtitterell8","completby":"jtitterell8","note":"policy"},
                            {"asunto":"Senior Cost Accountant","state":false,"startdate":"1/18/2021","expirationdate":"3/28/2021","enddate":"10/21/2020","accounts":"Doel","telephono":"914-919-1605","responsable":"Talya","createby":"tdoel9","updateby":"tdoel9","completby":"tdoel9","note":"algorithm"}],
                "table_actividades":[{"name":"Bonita Tallet","type":"BMW","state":false,"responsable":"Bonita","startdate":"5/22/2021","numberactivity":1,"createby":"btallet0","updateby":"btallet0"},
{"name":"Imojean Lacotte","type":"Ford","state":false,"responsable":"Imojean","startdate":"5/15/2021","numberactivity":2,"createby":"ilacotte1","updateby":"ilacotte1"},
{"name":"Emmy Quant","type":"Lexus","state":false,"responsable":"Emmy","startdate":"2/19/2021","numberactivity":3,"createby":"equant2","updateby":"equant2"},
{"name":"Leoline Grzelewski","type":"Buick","state":false,"responsable":"Leoline","startdate":"12/23/2020","numberactivity":4,"createby":"lgrzelewski3","updateby":"lgrzelewski3"},
{"name":"Gallagher Rohlf","type":"Ford","state":true,"responsable":"Gallagher","startdate":"3/7/2021","numberactivity":5,"createby":"grohlf4","updateby":"grohlf4"},
{"name":"Calvin Lasham","type":"Chevrolet","state":false,"responsable":"Calvin","startdate":"12/30/2020","numberactivity":6,"createby":"clasham5","updateby":"clasham5"},
{"name":"Lovell Mowen","type":"Mercedes-Benz","state":false,"responsable":"Lovell","startdate":"2/12/2021","numberactivity":7,"createby":"lmowen6","updateby":"lmowen6"},
{"name":"Jessalyn Larose","type":"Pontiac","state":false,"responsable":"Jessalyn","startdate":"3/25/2021","numberactivity":8,"createby":"jlarose7","updateby":"jlarose7"},
{"name":"Coleen Tompion","type":"Mazda","state":false,"responsable":"Coleen","startdate":"3/19/2021","numberactivity":9,"createby":"ctompion8","updateby":"ctompion8"},
                                {"name":"Brien Chittenden","type":"Ford","state":true,"responsable":"Brien","startdate":"10/9/2020","numberactivity":10,"createby":"bchittenden9","updateby":"bchittenden9"}],
                "table_vistas":[{"name":"Willie McKimm","startday":"12/30/2020","endday":"7/26/2021","responsable":"Willie","createby":"wmckimm0","state":false},
{"name":"Kristos Hainge","startday":"5/3/2021","endday":"6/27/2021","responsable":"Kristos","createby":"khainge1","state":true},
{"name":"Roi Rojel","startday":"1/4/2021","endday":"10/10/2020","responsable":"Roi","createby":"rrojel2","state":true},
{"name":"Woodman Riordan","startday":"8/19/2020","endday":"3/8/2021","responsable":"Woodman","createby":"wriordan3","state":false},
{"name":"Kimbra Colliss","startday":"4/29/2021","endday":"1/1/2021","responsable":"Kimbra","createby":"kcolliss4","state":false},
{"name":"Rowland Lodden","startday":"12/16/2020","endday":"4/23/2021","responsable":"Rowland","createby":"rlodden5","state":true},
{"name":"Christean Casserley","startday":"11/14/2020","endday":"7/20/2021","responsable":"Christean","createby":"ccasserley6","state":false},
{"name":"Ogdon Kohnen","startday":"10/23/2020","endday":"11/17/2020","responsable":"Ogdon","createby":"okohnen7","state":false},
{"name":"Thadeus Appleby","startday":"2/4/2021","endday":"9/7/2020","responsable":"Thadeus","createby":"tappleby8","state":true},
                            {"name":"Mallory Pickrell","startday":"7/2/2021","endday":"3/23/2021","responsable":"Mallory","createby":"mpickrell9","state":false}],
                "table_recordatorios":[{"client":"Karlen Franzolini","factura":"0378-5501","monto":"$0.52","statefactura":true,"experydate":"3/12/2021","delaynumber":1,"lastmanagementdate":"6/16/2021","lastmanagementcoment":"Tiehm's Beardtongue","state":true,"note":"Mylan Pharmaceuticals Inc.","aviso":"Skibox"},
{"client":"Dee Freiburger","factura":"53808-0979","monto":"$4.00","statefactura":true,"experydate":"11/3/2020","delaynumber":2,"lastmanagementdate":"12/18/2020","lastmanagementcoment":"Syrian-privet","state":true,"note":"State of Florida DOH Central Pharmacy","aviso":"Camido"},
{"client":"Annalise McVicar","factura":"55289-593","monto":"$3.09","statefactura":false,"experydate":"7/23/2021","delaynumber":3,"lastmanagementdate":"5/19/2021","lastmanagementcoment":"Common Mare's-tail","state":false,"note":"PD-Rx Pharmaceuticals, Inc.","aviso":"Kare"},
{"client":"Allie Gainsbury","factura":"66336-012","monto":"$5.16","statefactura":true,"experydate":"3/26/2021","delaynumber":4,"lastmanagementdate":"4/14/2021","lastmanagementcoment":"Supine Bean","state":true,"note":"Dispensing Solutions, Inc.","aviso":"Devpulse"},
{"client":"Aldus Jarrold","factura":"36987-2904","monto":"$1.00","statefactura":true,"experydate":"9/28/2020","delaynumber":5,"lastmanagementdate":"12/30/2020","lastmanagementcoment":"Philippine Lily","state":true,"note":"Nelco Laboratories, Inc.","aviso":"Youfeed"},
{"client":"Loren Napthine","factura":"49288-0404","monto":"$3.71","statefactura":false,"experydate":"8/30/2020","delaynumber":6,"lastmanagementdate":"9/4/2020","lastmanagementcoment":"Woodland Buttercup","state":false,"note":"Antigen Laboratories, Inc.","aviso":"Flipbug"},
{"client":"Meaghan Boerder","factura":"67405-550","monto":"$4.31","statefactura":true,"experydate":"9/25/2020","delaynumber":7,"lastmanagementdate":"12/28/2020","lastmanagementcoment":"Fringed Amaranth","state":true,"note":"Harris Pharmaceutical, Inc","aviso":"Kazio"},
{"client":"Dulsea Leber","factura":"58668-2741","monto":"$7.50","statefactura":true,"experydate":"6/20/2021","delaynumber":8,"lastmanagementdate":"9/6/2020","lastmanagementcoment":"Shrubby Mayweed","state":false,"note":"Laboratoires Clarins S.A.","aviso":"Wordify"},
{"client":"Olia Cardwell","factura":"10578-024","monto":"$5.71","statefactura":false,"experydate":"4/15/2021","delaynumber":9,"lastmanagementdate":"9/17/2020","lastmanagementcoment":"Tweedy's Milkvetch","state":true,"note":"Indiana Botanic Gardens","aviso":"Voolith"},
                                    {"client":"Esther Morphew","factura":"76284-001","monto":"$8.70","statefactura":true,"experydate":"8/17/2020","delaynumber":10,"lastmanagementdate":"9/30/2020","lastmanagementcoment":"Golden Pygmypoppy","state":true,"note":"Ningbo Timedo Medical Supply Co.,Ltd.","aviso":"Topdrive"}],
                "table_groupData":[{"idcuenta":1,"namecuenta":"Browsezoom","contact":"Mårten","address":"ayokel0@bbc.co.uk"},
{"idcuenta":2,"namecuenta":"Yamia","contact":"Françoise","address":"elehr1@epa.gov"},
{"idcuenta":3,"namecuenta":"Tagchat","contact":"Marylène","address":"pmoorwood2@toplist.cz"},
{"idcuenta":4,"namecuenta":"Feedbug","contact":"Desirée","address":"bthirtle3@ebay.co.uk"},
{"idcuenta":5,"namecuenta":"Meejo","contact":"Lucrèce","address":"cmorefield4@last.fm"},
{"idcuenta":6,"namecuenta":"Mydo","contact":"Yú","address":"iminards5@sphinn.com"},
{"idcuenta":7,"namecuenta":"Centizu","contact":"Almérinda","address":"nrichings6@usgs.gov"},
{"idcuenta":8,"namecuenta":"Kwimbee","contact":"Gaëlle","address":"lpringle7@wix.com"},
{"idcuenta":9,"namecuenta":"Camimbo","contact":"Véronique","address":"cwain8@netvibes.com"},
                                {"idcuenta":10,"namecuenta":"Pixonyx","contact":"Yú","address":"ohiggonet9@forbes.com"}],
                "table_datacuentas":[{"name":"Sidoney Stoney","rol":"Project Manager","telephone":"840-113-5072","email":"sstoney0@loc.gov"},
{"name":"Cristine Birtwell","rol":"Project Manager","telephone":"875-692-6813","email":"cbirtwell1@so-net.ne.jp"},
{"name":"Nataniel Satteford","rol":"Construction Expeditor","telephone":"747-953-1619","email":"nsatteford2@liveinternet.ru"},
{"name":"Maegan Beardwell","rol":"Construction Worker","telephone":"641-996-7229","email":"mbeardwell3@vimeo.com"},
{"name":"Celestia Consterdine","rol":"Construction Worker","telephone":"676-832-3633","email":"cconsterdine4@lulu.com"},
{"name":"Leisha Pietz","rol":"Construction Expeditor","telephone":"886-397-9321","email":"lpietz5@ox.ac.uk"},
{"name":"Ashlen Salway","rol":"Surveyor","telephone":"312-249-4048","email":"asalway6@alibaba.com"},
{"name":"Morley Jaffra","rol":"Architect","telephone":"911-400-2430","email":"mjaffra7@cisco.com"},
{"name":"Turner Cossar","rol":"Electrician","telephone":"116-370-8733","email":"tcossar8@phpbb.com"},
                                {"name":"Kacy MacAne","rol":"Project Manager","telephone":"274-310-8088","email":"kmacane9@ucoz.ru"}],
                "table_datacuentasdirecciones":[{"address":"663 Red Cloud Way","telephone":"794-864-5099","principal":"Research and Development"},
{"address":"62408 Killdeer Junction","telephone":"226-418-5215","principal":"Legal"},
{"address":"534 Nobel Street","telephone":"993-331-9620","principal":"Business Development"},
{"address":"19 Golden Leaf Terrace","telephone":"232-319-3963","principal":"Engineering"},
{"address":"033 Burrows Point","telephone":"784-825-1097","principal":"Business Development"},
{"address":"48471 Melby Avenue","telephone":"743-678-9830","principal":"Training"},
{"address":"9372 Pleasure Hill","telephone":"656-998-3671","principal":"Business Development"},
{"address":"6 High Crossing Alley","telephone":"244-939-9878","principal":"Engineering"},
{"address":"7 Forster Pass","telephone":"678-473-9064","principal":"Sales"},
                                {"address":"484 Bluejay Hill","telephone":"726-853-3736","principal":"Research and Development"}],
                "table_datalistaprecios":[{"codproducto":"58118-7927","description":"Removal of Drainage Device from Upper Bone, Perc Approach","monto":"$1.57","preciounidad":"$510.83M"},
{"codproducto":"17271-107","description":"Drainage of L Ant Tib Art, Perc Endo Approach, Diagn","monto":"$7.54","preciounidad":"n/a"},
{"codproducto":"59572-630","description":"Insert Intralum Dev in L Less Saphenous, Perc Endo","monto":"$4.01","preciounidad":"$424.11M"},
{"codproducto":"17478-932","description":"Extirpation of Matter from R Eustach Tube, Perc Approach","monto":"$1.69","preciounidad":"$4.24B"},
{"codproducto":"0069-2250","description":"Release Right Lung, Percutaneous Approach","monto":"$7.80","preciounidad":"$157.67M"},
{"codproducto":"59762-5025","description":"Release Pudendal Nerve, Percutaneous Approach","monto":"$6.18","preciounidad":"$4.08B"},
{"codproducto":"36987-2401","description":"Dilate 1 Cor Art, Bifurc, w Intralum Dev, Open","monto":"$0.65","preciounidad":"$377.45M"},
{"codproducto":"57243-159","description":"Supplement Cul-de-sac with Nonaut Sub, Open Approach","monto":"$4.16","preciounidad":"$21.55M"},
{"codproducto":"57955-2071","description":"Restriction of Right Neck Lymphatic, Open Approach","monto":"$9.27","preciounidad":"$92.34B"},
                                {"codproducto":"0904-6007","description":"Removal of Drainage Device from Coccygeal Jt, Perc Approach","monto":"$7.22","preciounidad":"$172.02M"}],
                "table_datavistas":[{"date":"5/22/2021","account":"Creavin","timetravel":"8:52 AM","timepreparation":"1:48 PM","starttime":"1:42 AM","duration":"2:03 PM","endtime":"5:48 PM"},
{"date":"3/26/2021","account":"Colthurst","timetravel":"4:46 AM","timepreparation":"5:01 AM","starttime":"3:23 PM","duration":"3:51 AM","endtime":"1:13 AM"},
{"date":"6/3/2021","account":"Boame","timetravel":"1:22 PM","timepreparation":"8:08 PM","starttime":"12:47 PM","duration":"4:04 AM","endtime":"9:24 PM"},
{"date":"7/29/2021","account":"Ianelli","timetravel":"7:53 AM","timepreparation":"1:00 AM","starttime":"4:48 AM","duration":"5:14 AM","endtime":"12:18 AM"},
{"date":"12/13/2020","account":"Silby","timetravel":"11:03 AM","timepreparation":"5:51 PM","starttime":"4:58 PM","duration":"10:18 AM","endtime":"4:48 PM"},
{"date":"1/20/2021","account":"Niland","timetravel":"5:35 AM","timepreparation":"9:21 PM","starttime":"2:12 PM","duration":"12:52 PM","endtime":"1:21 AM"},
{"date":"12/4/2020","account":"Heynel","timetravel":"9:27 PM","timepreparation":"12:26 AM","starttime":"4:41 PM","duration":"1:58 AM","endtime":"12:27 PM"},
{"date":"12/22/2020","account":"Hynard","timetravel":"9:56 PM","timepreparation":"8:50 PM","starttime":"5:37 AM","duration":"4:41 AM","endtime":"8:54 AM"},
{"date":"3/27/2021","account":"Lavigne","timetravel":"4:13 AM","timepreparation":"2:19 PM","starttime":"12:03 AM","duration":"7:07 PM","endtime":"10:39 AM"},
                                {"date":"3/2/2021","account":"Jacquest","timetravel":"11:34 AM","timepreparation":"8:06 PM","starttime":"8:50 PM","duration":"9:18 PM","endtime":"1:49 PM"}],
                "list_select":[{"listId":"1","vendedor":"Huberto Longo","zona":"America/Guatemala","hacienda":"Beijing University of Science and Technology"},
                            {"listId":"2","vendedor":"Seamus Domico","zona":"America/Sao_Paulo","hacienda":"Capilano College"},
                            {"listId":"3","vendedor":"Sunny Crick","zona":"Asia/Kuala_Lumpur","hacienda":"Université de Thiès"},
                            {"listId":"4","vendedor":"Consuelo Giocannoni","zona":"Africa/Casablanca","hacienda":"École des Hautes Études Commerciales"},
                            {"listId":"5","vendedor":"Carline Stanlock","zona":"America/Toronto","hacienda":"Hardin-Simmons University"}]
                        };
            var oModel = new sap.ui.model.json.JSONModel(oData);
			oModel.setSizeLimit(10000);
			this.setModel(oModel);
		}
	});
});
